#server:
#  port: 8080
#spring:
#  application:
#    name: finance-platform
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#
